<a href="https://colab.research.google.com/github/agussutaa/Tugas-Algoritma/blob/main/2208541012_Putu_Agus_Arya_Suta_Tugas_V.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nama : Putu Agus Arya Suta

NIM :220854012

Kelas : A


**Pertemuan 5 Algoritma dan Struktur Data**

Pada pertemuan kali ini ada beberapa pembahasan mengenai materi pendahuluan diantaranya sebagai berikut.


1.   List 2 Dimensi
2.   Tuples
3. Dictionaries
4. Fungsi pada Python
5. Numpy







1. List 2 Dimensi

In [ ]:
#Pada latihan kali ini kita akan menunjukkan list 2 dimensi
#umunya list 2 dimensi untuk menampilkan list di dalam list contohnya itu matriks
#contohnya pada dibawah ini didefinisikan 4 buah list dalam satu list bernama matriks
matriks = [
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,5],
    [16,17,18,19,20]
]
#selanjutnya akan dieksekusi untuk mencetak list matriks yang telah didefinisikan sebelumnya
print(matriks)
#pada hasil terlihat hasil masih berupa list matriks ukuran 1 x 5 sebanyak 4 list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 5], [16, 17, 18, 19, 20]]


In [ ]:
#pada bagian ini kita akan menampilkan indeks pada list bernama matriks
#perlu diingat bahwa indeks selalu dimulai dari 0 dan diakhiri dengan -1
#sehingga ketika kita ingin memanggil list dengan indeks 1 maka akan tercetak list yakni [6,7,8,9,10]
matriks[1]

[6, 7, 8, 9, 10]

In [ ]:
#pada bagian ini bertujuan untuk memanggil jumlah list yang ada dari indeks 0 sampai indeks 2
#karena dari 0-2 terdapat 3 buah list, maka hasil akan tercetak 3
matriks[0][2]

3

In [ ]:
#pada bagian ini akan dipanggil list pada list matriks dengan indeks 0 sampai 2
#bedanya dengan kode sebelumnya yakni untuk menentukan banyaknya list yang ada, namun pada kode ini untuk memanggil list yang ada pada indeks tersebut
#ingat indeks terakhir selalu tidak ikut, sehingga list yang tercetak dimulai dari indeks 0 sampai indeks 1 saja
matriks[0:2]

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [ ]:
#sama seperti latihan sebelumnya, type digunakan untuk menentukan tipe jenis data
#pada kali ini akan ditentukan tipe data untuk list yang didefinisikan dengan matriks indeks 1
type(matriks[1])
#hasil menunjukkan bahwa tipe data pada matriks indeks 1 yakni list

list

In [ ]:
#tiap list di dalam list dapat digabungkan dengan menggunakan tanda +
#pada bagian ini akan dilakukan penggabungan matriks dengan indeks 1 [6,7,8,9,10] dan indeks 2 [11,12,13,14,,15]
matriks[1]+matriks[2]

[6, 7, 8, 9, 10, 11, 12, 13, 14, 5]

In [ ]:
#pada bagian ini akan ditentukan banyak list pada list bernama matriks
print(len(matriks))
#hasil menunjukkan bahwa terdapat 4 list yang disatukan dalam satu list bernama matriks

4


In [ ]:
#contoh lain dari penerapan list 2 dimensi adalah sebagai berikut.
#digunakan type for dengan matriks yang didefinisikan sebagai baris
for baris in matriks:
#selanjutnya akan dieksekusi dengan mencetak baris yang telah didefinisikan sebelumnya
  print (baris)
  #pada bagian ini pula kembali dilakukan perulangan dengan baris yang sebelumnya kembali didefinisikan sebagai kolom
  for kolom in baris:
    #dilanjutkan dengan eksekusi mencetak kolom yang sebelumnya sudah didefinisikan
    print(kolom)
#hasil dari penerapan list 2 dimensi dengan tipe perulangan for sebagai berikut.
#dapat dilihat untuk baris pada masing-masing berubah menjadi kolom (bentuk vertikal)

[1, 2, 3, 4, 5]
1
2
3
4
5
[6, 7, 8, 9, 10]
6
7
8
9
10
[11, 12, 13, 14, 5]
11
12
13
14
5
[16, 17, 18, 19, 20]
16
17
18
19
20


2. Tuples

In [ ]:
#latihan selanjutnya ialah tuple
#tuple itu mirip dengan list, bedanya tuple merupakan data yang tidak bisa dirubah sedangkan list bisa
#yang saya pahami perbedan list dan tuple yakni pada pendefinisian datanya. kalau list pakai kurung siku [] sedangkan tuples pakai kurung biasa ()
#selanjutnya untuk latihan awal didefinisikan tuple dengan nama angka dengan beberapa elemen
angka = (0,1,2,3,2,4,3,1)
#pada bagian ini akan dieksekusi tuples bernama angka dengan indeks 4. Ingat! indeks dimulai dari 0 sampai -1
print(angka[4])
#hasil menunjjukan tuple angka dengan indeks 4 adalah 2

2


In [ ]:
#pada bagian ini akan ditunjukkan jenis dari variabel angka
type(angka)
#hasil menunjukkan bahwa data yang didefnisikan sebagai angka merupakan data dengan tipe tuple

tuple

In [ ]:
#pada bagian ini akan dicetak tuple bernama angka dengan indeks 3 sampai 5
#selalu diingat bahwa indeks terakhir tidak ikut dieksekusi sehingga yang tercetak hanyalah indeks 3 dan 4 saja
print (angka[3:5])
#pada hasil menunjukkan data tuple dengan indeks 3 dan 4 yakni (3,2)

(3, 2)


In [ ]:
#contoh dari tuple lainnya ialah sebagai berikut.
#digunakan tipe perulangan for untuk mencetak anggota dari tuple angka
#didefinisikan elemen pada angka dengan indeks batas akhir -1 yang mana artinya seluruh data pada tuple sampai indeks -2
for elemen in angka[:-1]:
  #selanjutnya pada bagian ini akan dicetak elemen yang telah didefinisikan sebelumnya
  print(elemen)

0
1
2
3
2
4
3


In [ ]:
#pada bagian ini akan dilakukan percobaan untuk mengganti atau menghapus data pada tuple
angka[0] = 3
angka.append[4]
angka.remove[3]
#hasil pada kode ini menjadi error bukan sebab kesalahan pada sintaks, melainkan karena data pada tuple memang mutlak dan tidak dapat dirubah
#beda halnya dengan data tipe list yang bisa direplace, dihapus, ditambah dan sebagainya


NameError: ignored

In [ ]:

angka.count(2)

2

3. Dictionaries

In [ ]:
#latihan selanjutnya ialah mengenai dictionaries
#data pada dictionaries itu digunakan ketika datanya saling berkaitan satu sama lain
#contoh pada kode berikut ini yakni dictionaries mengenai data orang
data_orang = {                         #selalu gunakan kurung kurawal pada dictionaries untuk mengaitkan data satu dan data selanjutnya
    'nama' : 'suta',
    "umur" : 19,
    'pernah_kelupaan?' : True
 }

In [ ]:
 #pada bagian ini akan dieksekusi dengan mencetak data_orang yakni berupa nama yang telah didefinisikan sebelumnya
 print(data_orang['nama'])

suta


In [ ]:
 #sama halnya dengan kode sebelumnya hanya menggunakan get untuk memanggil data berupa nama
 print(data_orang.get('nama'))

suta


In [ ]:
#pada bagian ini akan dicetak data orang namun menggunakan get untuk menambahkan data yang sebelumnya belum didefinisikan
#penambahan hanya tinggal menambahkan get lalu mendefinisikan apa yang ingin dipanggil
print(data_orang.get('tanggal_lahir', '11-April=2004'))

11-April=2004


In [ ]:
#pada bagian ini akan dicetak keseluruhan data untuk data orang
print(data_orang)
#hasil menunjukkan data-data yang telah didefinisikan berupa nama, umur, dan pertanyaan dengan nilai true atau false

{'nama': 'suta', 'umur': 19, 'pernah_kelupaan?': True}


In [ ]:
#data dari dictionaries sama halnya dengan data seperti list yang dapat ditambahkan
#ditambah kembali untuk data dengan definisi HP pada data orang
data_orang['HP'] = '088811188118'
#selanjutnya akan dicetak data orang dengan nama data HP
print(data_orang['HP'])

088811188118


In [ ]:
#karena sebelumnya telah dilakukan penambahan pada dictionaries yakni HP, maka kembali akan diperbarui untuk data orang dengan cara mencetak kembali data orang
print(data_orang)

{'nama': 'suta', 'umur': 19, 'pernah_kelupaan?': True, 'HP': '088811188118'}


In [ ]:
#latihan berikutnya penggunaan dictionaries untuk mencetak nomor HP berupa huruf
#didefinisikan data dictionaries bernama nomor yang terdiri dari data-data
nomor = {
    '0' : 'nol',
    '1' : 'satu',
    '2' : 'dua',
    '3' : 'tiga',
    '4' : 'empat',
    '5' : 'lima',
    '6' : 'enam',
    '7' : 'tujuh',
    '8' : 'delapan',
    '9' : 'sembilan'
}

In [ ]:
#selanjutnya pada bagian ini didefinisikan no_HP menggunakan kombinasi data input
no_HP = input("Masukkan no HP anda ")
#selanjutnya didefinisikan no angka yang akan diisi oleh data nomor yang sudah didefinisikan
no_angka = ""
#digunakan tipe data perulangan for dengan no HP yang didefinisikan sebelumnya menjadi isi
for isi in no_HP:
  #selanjutnya didefinisikan untuk no angka = no angka + nomor pada dictionaries ditambah dengan data isi yang sudah didefinisikan
  no_angka += nomor.get(isi) + ""
#akan dicetak untuk no angka dengan formula yang telah dirancang
print(no_angka)
#hasil menunjukkan ada data input yang masuk ketika di run
#dan data berupa angka tersebut berubah menjadi kata-kata misal 0 menjadi nol

Masukkan no HP anda 081222333444
noldelapansatuduaduaduatigatigatigaempatempatempat


4. Function

In [ ]:
#latihan berikutnya yakni mengenai fungsi pada python
#fungsi pada python bertujuan untuk mengurangi pengulangan data yang tinggi ketika membuat suatu program
#contohnya diberikan fungsi dengan nama waktu sampai yang didefinisikan dengan jarak dan waktu
def waktu_sampai (jarak,kecepatan):
  #selanjutnya kembali didefinisikan untuk waktu yakni dapat dioperasikan dengan jarak dibagi kecepatan
  waktu = jarak/kecepatan
  #pada bagian ini akan dicetak untuk waktu tersebut
  print(waktu)

In [ ]:
#kemudian sama dengan kode sebelumnya didefinisikan waktu tempuh yakni jarak dan kecepatan
def waktu_tempuh(jarak,kecepatan):
  #didefinisikan untuk waktu yakni jarak dibagi kecepatan
  waktu = jarak/kecepatan
  #selanjutnya akan dikembalikan untuk nilai waktu menggunakan fungsi return
  return waktu

In [ ]:
#Pada bagian ini akan didefinisikan jarak dan kecepatan untuk waktu sampai dan waktu tempuh masing-masing yakni 100 dan 80
waktu_sampai (100,80)
waktu_tempuh (100,80)
#didefinisikan a sebagai waktu sampai dengan jarak 100 dan kecepatan 80
a = waktu_sampai (100,80)
#didefinisikan b sebagai waktu tempuh dengan jarak 100 dan kecepatan 80
b = waktu_tempuh (100,80)
#selanjutnya akan dicetak untuk a dan b
print (a)
print (b)

1.25
1.25
None
1.25


In [ ]:
#Latihan berikutnya ialah menggunakan fungsi untuk menentukan median dari suatu data yang diberikan
#didefinisikan median yang terdiri dari x,y, dan z
def median (x,y,z):
  #dengan menggunakan tipe data if dengan syarat diberikan
  if x < y and y < z or x > y and y > z:
    #selanjutnya akan dikembalikan untuk nilai y
    return y
  if y < x and x < z or y > x and x > z:
    return x
  if z < x and y < z or z > x and y > z:
    return z
  #berlaku seterusnya untuk x,y dan z

In [ ]:
#pada bagian ini akan dicetak nilai median pada data, dengan data diberikan untuk penentuan median
print("Nilai median pada data:", median(2,3,5))
print("Nilai median pada data:", median(10,7,11))
#hasil pada data pertama yakni 3, karena setelah data terurut 3 merupakan nilai tengah
#pada percobaan kedua yakni 10, karena setelah data terurut 10 merupakan nilai tengah

Nilai median pada data: 3
Nilai median pada data: 10


5. Numpy

In [ ]:
#Latihan berikutnya yaitu Numpy (Numerical Python)
#pada dasarnya, numpy semacam pustaka di python yang memiliki keunggulan untuk menghitung vektor ataupun matriks
#sebelum memulai, terlebih dahulu kita akan memanggil pustaka yang ada dengan import numpy as np
import numpy as np

In [ ]:
#serta mengimport pandas as pd
import pandas as pd

5.1 Perintah Dasar pada Numpy

In [ ]:
#pada bagian ini didefinisikan vektor dengan numpy array bernama a sebagai berikut.
a = np.array([0,1,2,3,4])
#selanjutnya akan dicetak untuk a
print (a)
#hasil menunjukkan vektor atau matriks ukuran 1 x 5

[0 1 2 3 4]


In [ ]:
#sama halnya dengan program sebelumnya, didefinisikan b sebagai matriks dengan numpy array
b = np.array([[5,6,7,8],[9,8,7,6]])
#selanjutnya akan dicetak b
print (b)
#hasil menunjukkan matriks dengan ukurang 2 x 4

[[5 6 7 8]
 [9 8 7 6]]


In [ ]:
#pada bagian ini didefinisikan untuk c sebagai matriks dengan numpy array sebagai berikut.
c = np.array ([[[0,1,2,3],[4,5,6,7]],
               [[8,9,8,7], [6,5,4,3]],
               [[1,2,3,4], [5,6,7,8]]])
#selanjutnya akan dicetak untuk c
print (c)
#hasil menunjukkan 3 buah matriks ukuran 2 x 4 dalam satu kesatuan list

[[[0 1 2 3]
  [4 5 6 7]]

 [[8 9 8 7]
  [6 5 4 3]]

 [[1 2 3 4]
  [5 6 7 8]]]


In [ ]:
#ndim merupakan tipe data untuk menunjukkan dimensi dari suatu data
#akan ditunjukkan untuk dimensi dari a
a.ndim
#didapat a merupakan list dengan dimensi 1

1

In [ ]:
#akan ditunjukkan untuk dimensi dari b
b.ndim
#didapat b merupakan list dengan dimensi 2

2

In [ ]:
#akan ditunjukkan untuk dimensi dari c
c.ndim
#didapat c merupakan list dengan dimensi 3

3

In [ ]:
#shape digunakan untuk menentukan ukuran  variabel data
#akan ditunjukkan untuk ukuran dari a
a.shape

(5,)

In [ ]:
#akan ditunjukkan untuk ukuran dari b
b.shape

(2, 4)

In [ ]:
#akan ditunjukkan untuk ukuran dari c
c.shape

(3, 2, 4)

5.2 Memanggil Anggota, Kolom dan Baris dengan *Numpy*

In [ ]:
#didefinisikan d sebagai list (matriks) dengan data sebagai berikut.
d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
#akan dicetak untuk variabel d
print(d)
#hasil menunjukkan untuk d yakni merupakan matriks dengan ukuran 3 x 4

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#pada matriks di python, sama seperti indeks baris dan kolom pertama selalu dimulai dari 0 bukan 1
#pada bagian ini akan dipanggil anggota matriks dengan baris ke 1 dan kolom ke 2
d[1,2]
#anggota dengan baris 1 dan kolom 2 adalah 7

7

In [ ]:
#akan dipanggil baris dengan indeks 0 pada variabel d sebagai berikut.
d[0,:]

array([1, 2, 3, 4])

In [ ]:
#akan dipanggil kolom dengan indeks 1 pada variabel d sebagai berikut.
d[:,1]

array([ 2,  6, 10])

In [ ]:
d[0,1:3]

array([2, 3])

In [ ]:
d[2,1:2:3]

array([10])

In [ ]:
#pada bagian ini akan direplace elemen pada d dengan baris 1 kolom 3 menjadi 200
d[1,3] = 200
#akan dicetak untuk d setelah terdapat perubahan pada elemen
print (d)

[[  1   2   3   4]
 [  5   6   7 200]
 [  9  10  11  12]]


5.3 Matriks pada *Numpy*

In [ ]:
#berikut adalah cara mencetak matriks di numpy dengan elemen 1 ukuran 2 x 3
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#sama seperti kode sebelumnya, pada bagian ini akan dicetak matriks pada numpy dengan elemen 0 dengan ukuran 3 x 2
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
#pada bagian ini akan dibuat suatu matriks identitas ukuran 4x4. 
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#pada bagian ini akan dicetak matriks 2 dimensi dengan tiap-tiap ukurannya yakni 3 x 4 serta elemennya 1
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
#pada bagian ini akan dicetak matriks berukuran 3x2 dengan tiap-tiap elemennya merupakan 9
np.full((3,2),9)

array([[9, 9],
       [9, 9],
       [9, 9]])

In [ ]:
#salah satu keistimewaan numpy ialah dapat membuat matriks acak
#dengan menggunakan tipe random kita dapat membuat matriks dengan elemen acak seperti contoh matriks berukuran 4x3
np.random.rand(4,3)

array([[0.2420363 , 0.29138896, 0.0926841 ],
       [0.04610901, 0.54866906, 0.05102507],
       [0.64326164, 0.47895915, 0.37922517],
       [0.75950463, 0.51266244, 0.09840543]])

In [ ]:
#kemudian pada bagian ini kita pula dapat membuat matriks acak dengan elemennya dapat ditentukan dengan batas berapa saja
#contoh akan dibuat matriks dengan elemen acak 1 sampai 10 serta matriksnya berukuran 3x4
np.random.randint(1,10, size=(3,4))

array([[9, 2, 8, 4],
       [9, 2, 4, 2],
       [9, 1, 3, 6]])

In [ ]:
#Pada latihan ini kita akan membuat matriks seperti contoh pada buku ajar algoritma dan struktur data
#didefinisikan variabel a merupakan matriks elemen 0 dengan ukuran 10x10
a = np.zeros((10,10))
print (a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
#pada bagian ini didefinisikan b matrik identitas ukuran 10x10
b = np.identity(10)
print(b)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
#selanjutnya pada bagian ini didefinisikan c sebagai hasil kali antara 9 dengan matriks identitas b
c = 9*b
#akan dicetak untuk c
print (c)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 9. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 9. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 9. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 9. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 9. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 9. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


In [ ]:
#didefinisikan d merupakan matriks elemen 1 dengan ukuran 8x8
d = np.ones((8,8))
#didefinisikan untuk e merupakan matriks identitas 8x8
e = np.identity(8)*8
#didefinisikan f sebagai hasil penjumlahan matriks d dan e
f = d+e
#selanjutnya akan dicetak matriks f
print (f)

[[9. 1. 1. 1. 1. 1. 1. 1.]
 [1. 9. 1. 1. 1. 1. 1. 1.]
 [1. 1. 9. 1. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 1. 9. 1. 1. 1.]
 [1. 1. 1. 1. 1. 9. 1. 1.]
 [1. 1. 1. 1. 1. 1. 9. 1.]
 [1. 1. 1. 1. 1. 1. 1. 9.]]


In [ ]:
#selanjutnya matriks c dengan batas yang disebut, didefinisikan sebagai f
c[1:-1,1:-1] = f
#akan dicetak untuk matriks c terbaru
print(c)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 9. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 9. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 9. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 9. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


In [ ]:
#didefinisikan matriks g merupakan matriks identitas 6x6 dikali dengan 9
g = np.identity(6)*9
#selanjutnya matriks c dengan batas yang disebut, didefinisikan sebagai g
c[2:-2,2:-2] = g
#cetak matriks c 
print (c)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 9. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 9. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 9. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 9. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


In [ ]:
#didefinisikan h, i, dan j sebagai berikut
h = np.ones((4,4))*2
i = np.identity(4)*7
j = h+i
print(j)

[[9. 2. 2. 2.]
 [2. 9. 2. 2.]
 [2. 2. 9. 2.]
 [2. 2. 2. 9.]]


In [ ]:
#selanjutnya matriks c dengan batas yang disebut, didefinisikan sebagai j
c[3:-3,3:-3] = j
#cetak untuk c
print(c)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 9. 2. 2. 2. 0. 1. 0.]
 [0. 1. 0. 2. 9. 2. 2. 0. 1. 0.]
 [0. 1. 0. 2. 2. 9. 2. 0. 1. 0.]
 [0. 1. 0. 2. 2. 2. 9. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


In [ ]:
#didefinisikan k sebagai matriks identitas 2x2 dikali dengan 9
k = np.identity(2)*9
#selanjutnya matriks c dengan batas yang disebut, didefinisikan sebagai k
c[4:-4,4:-4] = k
#terakhir, cetak c untuk mendapatkan hasil terbaru untuk matriks c
print(c)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 9. 2. 2. 2. 0. 1. 0.]
 [0. 1. 0. 2. 9. 0. 2. 0. 1. 0.]
 [0. 1. 0. 2. 0. 9. 2. 0. 1. 0.]
 [0. 1. 0. 2. 2. 2. 9. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


5.4 *Copy* pada *Numpy*

In [ ]:
#latihan berikutnya ialah copy pada numpy
#didefinisikan variabel a dengan numpy array merupakan suatu vektor
a = np.array([1,2,3,4,5])
#akan dicetak untuk vektor a
print (a)

[1 2 3 4 5]


In [ ]:
#dengan menggunakan tanda =, kita sudah dapat secara otomatis mengcopy suatu data dengan variabel berbeda
#selanjutnya didefinisikan b sama dengan a
b = a
#akan dicetak untuk nilai b
print (b)

[1 2 3 4 5]


In [ ]:
#pada bagian ini, nilai dari b dengan indeks 0 diganti dengan elemen baru yakni 10
b[0] = 10
#akan dicetak untuk b terbaru
print(b)

[10  2  3  4  5]


In [ ]:
print(a)
#pada bagian ini nilai pula turut mengalami perubahan berdasarkan definisi sebelumnya b = a

[10  2  3  4  5]


In [ ]:
#contoh lainnya didefinisikan untuk c merupakan vektor dengan numpy array
c = np.array([1,2,3,4,5])
#akan dicetak vektor c
print (c)

[1 2 3 4 5]


In [ ]:
#selanjutnya didefinisikan untuk d merupakan hasil copy dari variabel c
d = c.copy()
#akan dicetak untuk variabel d
print (d)

[1 2 3 4 5]


In [ ]:
#akan direplace untuk elemen di variabel d menjadi 1000
d[1] = 1000
#akan dicetak untuk variabel d terbaru
print (d)

[   1 1000    3    4    5]


In [ ]:
#pada bagian ini akan dicetak untuk variabel c
print (c)
#hasil menunjukkan tidak terdapat perubahan
#hal tersebut terjadi karena definisi dari variabel d merupakan copy dari variabel c, sehingga variabel c tetap seperti semula
#beda halnya ketika kasusnya d = c, apabila elemen di d mengalami perubahan maka secara otomatis berlaku juga untuk elemen di variabel c

[1 2 3 4 5]


5.5 Operasi Matematika pada Numpy

In [10]:
#didefinisikan variabel a merupakan vektor dengan numpy array
a = np.array ([1,2,3])
#akan dieksekusi untuk variabel a dijumlah dengan 2
a+2

array([3, 4, 5])

In [22]:
#didefinisikan variabel b merupakan vektor dengan numpy array
b = np.array ([4,5,6])
#akan dicetak b
print (b)

[4 5 6]


In [ ]:
#pada bagian ini akan diuji untuk perkalian variabel a dan b
a*b

In [12]:
#akan ditentukan nilai cos dari variabel a
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

5.6 Perkalian Matriks pada *Numpy*

In [13]:
#didefinisikan a merupakan matriks dengan numpy array
a = np.array([[1,2,3,4],[5,6,7,8]])
#akan dicetak untuk matriks a
print (a)

[[1 2 3 4]
 [5 6 7 8]]


In [14]:
#didefinisikan b merupakan matriks dengan numpy array
b = np.array([[9,10,11,12],[13,14,15,16]])
##akan dicetak untuk matriks b
print (b)

[[ 9 10 11 12]
 [13 14 15 16]]


In [15]:
#didefinisikan variabel c sebagai hasil kali matriks a dan matriks b
c = a*b
#akan dicetak untuk c
print (c)

[[  9  20  33  48]
 [ 65  84 105 128]]


5.7 *Min*, *max*, dan *sum* pada *Numpy*

In [18]:
#latihan numpy berikutnya ialah menentukan nilai min, max dan jumlah
#didefinisikan untuk matriks variabel a berukuran 3x4
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
#akan dicetak untuk matriks a
print (a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
#pada bagian ini akan ditentukan nilai minimum pada variabel a menggunakan np.min
#didefinisikan b merupakan nilai minimum variabel a
b = np.min(a)
#akan dicetak untuk nilai b
print (b)

1


In [20]:
#pada bagian ini akan ditentukan nilai maksimum pada variabel a menggunakan np.max
#didefinisikan c merupakan nilai maksimum variabel a
c = np.max(a)
#akan dicetak untuk nilai c
print (c)

12


In [21]:
#pada bagian ini akan ditentukan nilai total atau jumlah pada variabel a menggunakan np.sum
#didefinisikan d merupakan nilai total untuk variabel a
d = np.sum(a)
##akan dicetak untuk nilai d
print(d)

78
